# Generated by Django 5.1.7 on 2025-03-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('postcode', models.CharField(default='DUMMY', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('postcodenospace', models.CharField(default='DUMMY', max_length=100)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('longitude', models.CharField(max_length=100, null=True)),
                ('easting', models.CharField(max_length=100, null=True)),
                ('northing', models.CharField(max_length=100, null=True)),
                ('county', models.CharField(max_length=100, null=True)),
                ('district', models.CharField(max_length=100, null=True)),
                ('ward', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('population', models.CharField(max_length=100, null=True)),
                ('households', models.CharField(max_length=100, null=True)),
                ('rural_urban', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('altitude', models.CharField(max_length=100, null=True)),
                ('london_zone', models.CharField(max_length=100, null=True)),
                ('nearest_station', models.CharField(max_length=100, null=True)),
                ('distance_to_station', models.CharField(max_length=100, null=True)),
                ('postcode_area', models.CharField(max_length=100, null=True)),
                ('postcode_district', models.CharField(max_length=100, null=True)),
                ('police_force', models.CharField(max_length=100, null=True)),
                ('water_company', models.CharField(max_length=100, null=True)),
                ('average_income', models.CharField(max_length=100, null=True)),
                ('sewage_company', models.CharField(max_length=100, null=True)),
                ('travel_to_work_area', models.CharField(max_length=100, null=True)),
                ('distance_to_sea', models.CharField(max_length=100, null=True)),
                ('property_type', models.CharField(max_length=100, null=True)),
                ('roads', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
