# Generated by Django 5.2 on 2025-04-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=10)),
                ('latitude', models.FloatField(blank=True)),
                ('longitude', models.FloatField(blank=True)),
                ('easting', models.IntegerField(blank=True)),
                ('northing', models.IntegerField(blank=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('district_code', models.CharField(blank=True, max_length=10, null=True)),
                ('ward_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('county_code', models.CharField(blank=True, max_length=10, null=True)),
                ('parish', models.CharField(blank=True, max_length=100, null=True)),
                ('national_park', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('households', models.IntegerField(blank=True, null=True)),
                ('built_up_area', models.CharField(blank=True, max_length=100, null=True)),
                ('rural_urban', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('altitude', models.IntegerField(blank=True, null=True)),
                ('london_zone', models.IntegerField(blank=True, null=True)),
                ('local_authority', models.CharField(blank=True, max_length=100, null=True)),
                ('census_output_area', models.CharField(blank=True, max_length=20, null=True)),
                ('index_of_multiple_deprivation', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('nearest_station', models.CharField(blank=True, max_length=100, null=True)),
                ('distance_to_station', models.FloatField(blank=True, null=True)),
                ('postcode_area', models.CharField(blank=True, max_length=10, null=True)),
                ('postcode_district', models.CharField(blank=True, max_length=10, null=True)),
                ('police_force', models.CharField(blank=True, max_length=100, null=True)),
                ('water_company', models.CharField(blank=True, max_length=100, null=True)),
                ('average_income', models.FloatField(blank=True, null=True)),
                ('sewage_company', models.CharField(blank=True, max_length=100, null=True)),
                ('travel_to_work_area', models.CharField(blank=True, max_length=100, null=True)),
                ('distance_to_sea', models.FloatField(blank=True, null=True)),
                ('constituency_name_2024', models.CharField(blank=True, max_length=100, null=True)),
                ('property_type', models.CharField(blank=True, max_length=50, null=True)),
                ('roads', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
